### ISSUE TITLE
Accessing new message component without having new messages

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chat#43]
**Describe the bug**

You can have a `new message` component appear and stay there (until you refresh the page)
![image](https://user-images.githubusercontent.com/88248797/203924644-b82b8ee2-7e74-4b80-b30b-d71e8513a532.png)

**To Reproduce**
1. Go to 'open our chat app' (didn't post a link to avoid random joiners). Edit: Wait if someone visit this repo, they can see the link on the right side of the repo https://chat.freecodecamp.org/
2. Press the tab until the message component appear
3. Have that component follow you between rooms

**Expected behavior**
Small issue, just wanted to report it. We can have some logic to not render it if there are no new messages.

**Additional context**
if you think deep about it, it may be a feature 🤔

**Comment by raisedadead** [comment]
Please open an issue on the rocket chat repo. We do not maintain the code.
